### ISSUE TITLE
Installed the add-on, where can I see the button?

### ISSUE THREAD

**Issue by IcedRooibos** [SaltyAimbOtter/Thunderbird-ProtonCalendar-Addon#1]
Hi there,

I am on Thunderbird 102. I have installed the add-on but the button doesn't seem to show up on my toolbar. Where would I find the button?

![image](https://user-images.githubusercontent.com/47491349/202973919-568a7a09-3aa9-4f71-b80c-282f7c175e02.png)

**Comment by IcedRooibos** [comment]
I was looking in the wrong place, it's here!
![image](https://user-images.githubusercontent.com/47491349/202977141-3876cd80-894e-4aee-8ab6-f30595d01025.png)

**Comment by SaltyAimbOtter** [comment]
Great!
